# Site settings
title: Jinsun-Lee
description: 'Divide and Conquer'
url: 'https://jinsun-lee.github.io'
baseurl: ''
profilepic: '/images/sun.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '91805d646c.js'

author:
  name: 'Jinsun-Lee'
  email: withire32@kakao.com
#  twitter_username: whatif1g0
#  facebook_username: joshgerdes
  github_username:  Jinsun-Lee
  linkedin_username:  진선-이-308193269
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
